SET ECHO ON
SPOOL pat_schema_output.txt

-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-05-02 18:56:03 SGT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

-- Group Number: G027

DROP TABLE driver CASCADE CONSTRAINTS;

DROP TABLE driver_language CASCADE CONSTRAINTS;

DROP TABLE driver_training CASCADE CONSTRAINTS;

DROP TABLE feature CASCADE CONSTRAINTS;

DROP TABLE language CASCADE CONSTRAINTS;

DROP TABLE location CASCADE CONSTRAINTS;

DROP TABLE location_type CASCADE CONSTRAINTS;

DROP TABLE make CASCADE CONSTRAINTS;

DROP TABLE model CASCADE CONSTRAINTS;

DROP TABLE national_olympic_committee CASCADE CONSTRAINTS;

DROP TABLE official CASCADE CONSTRAINTS;

DROP TABLE training_module CASCADE CONSTRAINTS;

DROP TABLE trip CASCADE CONSTRAINTS;

DROP TABLE vehicle CASCADE CONSTRAINTS;

DROP TABLE vehicle_feature CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE driver (
    driver_id                 CHAR(4) NOT NULL,
    driver_giv_name           VARCHAR2(50) NOT NULL,
    driver_fam_name           VARCHAR2(50) NOT NULL,
    driver_licence_num        CHAR(18) NOT NULL,
    driver_dob                DATE NOT NULL,
    driver_sec_clear_lvl      CHAR(1) DEFAULT 'R' NOT NULL,
    driver_suspended          CHAR(1) DEFAULT 'N' NOT NULL,
    driver_completed_tm_count NUMBER(3) NOT NULL
);

ALTER TABLE driver
    ADD CONSTRAINT chk_sec_clear_lvl CHECK ( driver_sec_clear_lvl IN ( 'F', 'R' ) );

ALTER TABLE driver
    ADD CONSTRAINT chk_suspended CHECK ( driver_suspended IN ( 'N', 'Y' ) );

COMMENT ON COLUMN driver.driver_id IS
    'ID of the driver';

COMMENT ON COLUMN driver.driver_giv_name IS
    'Given name of the driver';

COMMENT ON COLUMN driver.driver_fam_name IS
    'Family name of the driver';

COMMENT ON COLUMN driver.driver_licence_num IS
    'Licence number of the driver';

COMMENT ON COLUMN driver.driver_dob IS
    'Date of birth of the driver';

COMMENT ON COLUMN driver.driver_sec_clear_lvl IS
    'Security clearance level of the driver';

COMMENT ON COLUMN driver.driver_suspended IS
    'Whether the driver is suspended or not';

COMMENT ON COLUMN driver.driver_completed_tm_count IS
    'Total count of all training modules the driver has completed';

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( driver_id );

ALTER TABLE driver ADD CONSTRAINT driver_uq UNIQUE ( driver_licence_num );

CREATE TABLE driver_language (
    driver_id CHAR(4) NOT NULL,
    lang_code CHAR(2) NOT NULL
);

COMMENT ON COLUMN driver_language.driver_id IS
    'ID of the driver';

COMMENT ON COLUMN driver_language.lang_code IS
    'ISO639-1 code of the language';

ALTER TABLE driver_language ADD CONSTRAINT driver_language_pk PRIMARY KEY ( driver_id,
                                                                            lang_code );

CREATE TABLE driver_training (
    dt_id              NUMBER(4) NOT NULL,
    driver_id          CHAR(4) NOT NULL,
    tm_code            VARCHAR2(10) NOT NULL,
    dt_completion_date DATE NOT NULL
);

COMMENT ON COLUMN driver_training.dt_id IS
    'ID of the driver training (surrogate PK)';

COMMENT ON COLUMN driver_training.driver_id IS
    'ID of the driver';

COMMENT ON COLUMN driver_training.tm_code IS
    'Code of the training module';

COMMENT ON COLUMN driver_training.dt_completion_date IS
    'Date when the training module was completed by the driver';

ALTER TABLE driver_training ADD CONSTRAINT driver_training_pk PRIMARY KEY ( dt_id );

ALTER TABLE driver_training
    ADD CONSTRAINT driver_training_nk UNIQUE ( driver_id,
                                               tm_code,
                                               dt_completion_date );

CREATE TABLE feature (
    feature_id   NUMBER(4) NOT NULL,
    feature_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN feature.feature_id IS
    'ID of the feature (surrogate PK)';

COMMENT ON COLUMN feature.feature_name IS
    'Name of the feature';

ALTER TABLE feature ADD CONSTRAINT feature_pk PRIMARY KEY ( feature_id );

CREATE TABLE language (
    lang_code CHAR(2) NOT NULL,
    lang_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN language.lang_code IS
    'ISO639-1 code of the language';

COMMENT ON COLUMN language.lang_name IS
    'Name of the language';

ALTER TABLE language ADD CONSTRAINT language_pk PRIMARY KEY ( lang_code );

CREATE TABLE location (
    location_id      NUMBER(4) NOT NULL,
    location_name    VARCHAR2(50) NOT NULL,
    location_address VARCHAR2(100) NOT NULL,
    lt_id            NUMBER(4) NOT NULL
);

COMMENT ON COLUMN location.location_id IS
    'ID of the location';

COMMENT ON COLUMN location.location_name IS
    'Name of the location';

COMMENT ON COLUMN location.location_address IS
    'Address of the location';

COMMENT ON COLUMN location.lt_id IS
    'ID of the location type (surrogate PK)';

ALTER TABLE location ADD CONSTRAINT location_pk PRIMARY KEY ( location_id );

CREATE TABLE location_type (
    lt_id   NUMBER(4) NOT NULL,
    lt_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN location_type.lt_id IS
    'ID of the location type (surrogate PK)';

COMMENT ON COLUMN location_type.lt_name IS
    'Name of the location type';

ALTER TABLE location_type ADD CONSTRAINT location_type_pk PRIMARY KEY ( lt_id );

CREATE TABLE make (
    make_id   NUMBER(4) NOT NULL,
    make_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN make.make_id IS
    'ID of the make (surrogate PK)';

COMMENT ON COLUMN make.make_name IS
    'Name of the make';

ALTER TABLE make ADD CONSTRAINT make_pk PRIMARY KEY ( make_id );

CREATE TABLE model (
    model_id   NUMBER(4) NOT NULL,
    model_name VARCHAR2(50) NOT NULL,
    make_id    NUMBER(4) NOT NULL
);

COMMENT ON COLUMN model.model_id IS
    'ID of the model (surrogate PK)';

COMMENT ON COLUMN model.model_name IS
    'Name of the model';

COMMENT ON COLUMN model.make_id IS
    'ID of the make (surrogate PK)';

ALTER TABLE model ADD CONSTRAINT model_pk PRIMARY KEY ( model_id );

CREATE TABLE national_olympic_committee (
    noc_ioc_code   CHAR(3) NOT NULL,
    noc_name       VARCHAR2(50) NOT NULL,
    noc_population NUMBER(10) NOT NULL
);

COMMENT ON COLUMN national_olympic_committee.noc_ioc_code IS
    'IOC code of the NOC';

COMMENT ON COLUMN national_olympic_committee.noc_name IS
    'Name of the country/region the NOC is representing';

COMMENT ON COLUMN national_olympic_committee.noc_population IS
    'Population of the country/name the NOC is representing';

ALTER TABLE national_olympic_committee ADD CONSTRAINT national_olympic_committee_pk PRIMARY KEY ( noc_ioc_code );

CREATE TABLE official (
    official_olympic_id      CHAR(7) NOT NULL,
    official_giv_name        VARCHAR2(50) NOT NULL,
    official_fam_name        VARCHAR2(50) NOT NULL,
    official_role            VARCHAR2(50) NOT NULL,
    noc_ioc_code             CHAR(3) NOT NULL,
    chefdemission_olympic_id CHAR(7)
);

COMMENT ON COLUMN official.official_olympic_id IS
    'Olympic ID of the official';

COMMENT ON COLUMN official.official_giv_name IS
    'Given name of the official';

COMMENT ON COLUMN official.official_fam_name IS
    'Family name of the official';

COMMENT ON COLUMN official.official_role IS
    'Role of the official';

COMMENT ON COLUMN official.noc_ioc_code IS
    'IOC code of the NOC';

COMMENT ON COLUMN official.chefdemission_olympic_id IS
    'Olympic ID of the official';

ALTER TABLE official ADD CONSTRAINT official_pk PRIMARY KEY ( official_olympic_id );

CREATE TABLE training_module (
    tm_code          VARCHAR2(10) NOT NULL,
    tm_name          VARCHAR2(50) NOT NULL,
    tm_desc          VARCHAR2(100) NOT NULL,
    tm_length        NUMBER(2) NOT NULL,
    tm_expiry_period NUMBER(2) NOT NULL
);

COMMENT ON COLUMN training_module.tm_code IS
    'Code of the training module';

COMMENT ON COLUMN training_module.tm_name IS
    'Name of the training module';

COMMENT ON COLUMN training_module.tm_desc IS
    'Description of the training module';

COMMENT ON COLUMN training_module.tm_length IS
    'Length of the training module (expressed in days)';

COMMENT ON COLUMN training_module.tm_expiry_period IS
    'Expiry period of the training module (expressed in months)';

ALTER TABLE training_module ADD CONSTRAINT training_module_pk PRIMARY KEY ( tm_code );

CREATE TABLE trip (
    trip_id                      NUMBER(4) NOT NULL,
    vehicle_vin                  CHAR(17) NOT NULL,
    driver_id                    CHAR(4) NOT NULL,
    official_olympic_id          CHAR(7) NOT NULL,
    trip_num_of_passengers       NUMBER(3) NOT NULL,
    pickup_location_id           NUMBER(4) NOT NULL,
    trip_intend_pickup_datetime  DATE NOT NULL,
    trip_actual_pickup_datetime  DATE,
    dropoff_location_id          NUMBER(4) NOT NULL,
    trip_intend_dropoff_datetime DATE NOT NULL,
    trip_actual_dropoff_datetime DATE,
    lang_code                    CHAR(2) NOT NULL
);

COMMENT ON COLUMN trip.trip_id IS
    'ID of the trip (surrogate PK)';

COMMENT ON COLUMN trip.vehicle_vin IS
    'VIN (vehicle identification number) of the vehicle';

COMMENT ON COLUMN trip.driver_id IS
    'ID of the driver';

COMMENT ON COLUMN trip.official_olympic_id IS
    'Olympic ID of the official';

COMMENT ON COLUMN trip.trip_num_of_passengers IS
    'Number of passengers transported in the trip';

COMMENT ON COLUMN trip.pickup_location_id IS
    'ID of the location';

COMMENT ON COLUMN trip.trip_intend_pickup_datetime IS
    'Intended pickup date and time of the trip';

COMMENT ON COLUMN trip.trip_actual_pickup_datetime IS
    'Actual pickup date and time of the trip';

COMMENT ON COLUMN trip.dropoff_location_id IS
    'ID of the location';

COMMENT ON COLUMN trip.trip_intend_dropoff_datetime IS
    'Intended dropoff date and time of the trip';

COMMENT ON COLUMN trip.trip_actual_dropoff_datetime IS
    'Actual dropoff date and time of the trip';

COMMENT ON COLUMN trip.lang_code IS
    'ISO639-1 code of the language';

ALTER TABLE trip ADD CONSTRAINT trip_pk PRIMARY KEY ( trip_id );

ALTER TABLE trip ADD CONSTRAINT trip_nk UNIQUE ( vehicle_vin,
                                                 trip_intend_pickup_datetime );

ALTER TABLE trip ADD CONSTRAINT trip_uq UNIQUE ( vehicle_vin,
                                                 trip_intend_dropoff_datetime );

ALTER TABLE trip ADD CONSTRAINT trip_uq_2 UNIQUE ( driver_id,
                                                   trip_intend_pickup_datetime );

ALTER TABLE trip ADD CONSTRAINT trip_uq_3 UNIQUE ( driver_id,
                                                   trip_intend_dropoff_datetime );

CREATE TABLE vehicle (
    vehicle_vin              CHAR(17) NOT NULL,
    vehicle_regist_num       CHAR(7) NOT NULL,
    vehicle_year             NUMBER(4) NOT NULL,
    vehicle_odometer_reading NUMBER(8) NOT NULL,
    vehicle_seating_capacity NUMBER(3) NOT NULL,
    model_id                 NUMBER(4) NOT NULL
);

COMMENT ON COLUMN vehicle.vehicle_vin IS
    'VIN (vehicle identification number) of the vehicle';

COMMENT ON COLUMN vehicle.vehicle_regist_num IS
    'Registration plate number of the vehicle';

COMMENT ON COLUMN vehicle.vehicle_year IS
    'Year when the vehicle was manufactured';

COMMENT ON COLUMN vehicle.vehicle_odometer_reading IS
    'Current odometer reading of the vehicle';

COMMENT ON COLUMN vehicle.vehicle_seating_capacity IS
    'Number of seats in the vehicle';

COMMENT ON COLUMN vehicle.model_id IS
    'ID of the model (surrogate PK)';

ALTER TABLE vehicle ADD CONSTRAINT vehicle_pk PRIMARY KEY ( vehicle_vin );

ALTER TABLE vehicle ADD CONSTRAINT vehicle_uq UNIQUE ( vehicle_regist_num );

CREATE TABLE vehicle_feature (
    vehicle_vin CHAR(17) NOT NULL,
    feature_id  NUMBER(4) NOT NULL
);

COMMENT ON COLUMN vehicle_feature.vehicle_vin IS
    'VIN (vehicle identification number) of the vehicle';

COMMENT ON COLUMN vehicle_feature.feature_id IS
    'ID of the feature (surrogate PK)';

ALTER TABLE vehicle_feature ADD CONSTRAINT vehicle_feature_pk PRIMARY KEY ( vehicle_vin,
                                                                            feature_id );

ALTER TABLE official
    ADD CONSTRAINT chefdemission_official FOREIGN KEY ( chefdemission_olympic_id )
        REFERENCES official ( official_olympic_id );

ALTER TABLE driver_language
    ADD CONSTRAINT driver_driverlanguage FOREIGN KEY ( driver_id )
        REFERENCES driver ( driver_id );

ALTER TABLE driver_training
    ADD CONSTRAINT driver_drivertraining FOREIGN KEY ( driver_id )
        REFERENCES driver ( driver_id );

ALTER TABLE trip
    ADD CONSTRAINT driver_trip FOREIGN KEY ( driver_id )
        REFERENCES driver ( driver_id );

ALTER TABLE trip
    ADD CONSTRAINT dropofflocation_trip FOREIGN KEY ( dropoff_location_id )
        REFERENCES location ( location_id );

ALTER TABLE vehicle_feature
    ADD CONSTRAINT feature_vehiclefeature FOREIGN KEY ( feature_id )
        REFERENCES feature ( feature_id );

ALTER TABLE driver_language
    ADD CONSTRAINT language_driverlanguage FOREIGN KEY ( lang_code )
        REFERENCES language ( lang_code );

ALTER TABLE trip
    ADD CONSTRAINT language_trip FOREIGN KEY ( lang_code )
        REFERENCES language ( lang_code );

ALTER TABLE location
    ADD CONSTRAINT locationtype_location FOREIGN KEY ( lt_id )
        REFERENCES location_type ( lt_id );

ALTER TABLE model
    ADD CONSTRAINT make_model FOREIGN KEY ( make_id )
        REFERENCES make ( make_id );

ALTER TABLE vehicle
    ADD CONSTRAINT model_vehicle FOREIGN KEY ( model_id )
        REFERENCES model ( model_id );

ALTER TABLE official
    ADD CONSTRAINT noc_official FOREIGN KEY ( noc_ioc_code )
        REFERENCES national_olympic_committee ( noc_ioc_code );

ALTER TABLE trip
    ADD CONSTRAINT official_trip FOREIGN KEY ( official_olympic_id )
        REFERENCES official ( official_olympic_id );

ALTER TABLE trip
    ADD CONSTRAINT pickuplocation_trip FOREIGN KEY ( pickup_location_id )
        REFERENCES location ( location_id );

ALTER TABLE driver_training
    ADD CONSTRAINT trainingmodule_drivertraining FOREIGN KEY ( tm_code )
        REFERENCES training_module ( tm_code );

ALTER TABLE trip
    ADD CONSTRAINT vehicle_trip FOREIGN KEY ( vehicle_vin )
        REFERENCES vehicle ( vehicle_vin );

ALTER TABLE vehicle_feature
    ADD CONSTRAINT vehicle_vehiclefeature FOREIGN KEY ( vehicle_vin )
        REFERENCES vehicle ( vehicle_vin );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             0
-- ALTER TABLE                             41
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL OFF
SET ECHO OFF